!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        0100aNz1100110hOgI-Credit Memo:
          path: dataset/0100aNz1100110hOgI-Credit Memo
          prefix: SAMDEV
          versions:
            Version-1.0:
              modifiedDate: '2020-02-03 13:51:02'
        0111cNd1100110wDhC-CommitFromSRC-SFORG-b74f6bdb-6739-4f95-c4f2-258216b3d829:
          path: dataset/0111cNd1100110wDhC-CommitFromSRC-SFORG-b74f6bdb-6739-4f95-c4f2-258216b3d829
          prefix: AR_PREVIEW
          versions:
            '1':
              modifiedDate: '2020-02-14 11:20:57'
