!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        0100aNz1100110hOgI-Credit Memo:
          path: dataset/0100aNz1100110hOgI-Credit Memo
          prefix: SAMDEV
          standardFeature: false
          versions:
            Version-1.0:
              modifiedDate: '2020-03-13 09:18:27'
            Version-2.0:
              modifiedDate: '2020-02-03 13:55:59'
        0100aNz1100110hOgI-Jan24-Test4:
          path: dataset/0100aNz1100110hOgI-Jan24-Test4
          prefix: ncino-
          standardFeature: true
          versions:
            '24.2':
              modifiedDate: '2020-02-18 06:37:21'
        0100aNz1100110hOgI-CreditMemoCompare:
          path: dataset/0100aNz1100110hOgI-CreditMemoCompare
          prefix: SAMDEV
          standardFeature: false
          versions:
            '1':
              modifiedDate: '2020-03-16 14:02:58'
