!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    ? ''
    : features:
        01p6F00000QkOpC-Credit Memo:
          path: /01p6F00000QkOpC-Credit Memo
          prefix: SAMDEV
          standardFeature: false
          versions:
            Version-1.0:
              modifiedDate: '2020-02-14 07:00:53'
            Version-2.0:
              modifiedDate: '2020-02-14 07:24:16'
        01p6F00000QkOpC-Feature2:
          path: /01p6F00000QkOpC-Feature2
          prefix: SAMDEV
          standardFeature: false
          versions:
            '3.0':
              modifiedDate: '2020-02-14 09:38:33'
        0100bUe1100110eOsV-11:
          path: /0100bUe1100110eOsV-11
          prefix: ncino-
          standardFeature: true
          versions:
            '12':
              modifiedDate: '2020-02-17 11:04:35'
        01p6F00000QkOpC-MyFeature543-:
          path: /01p6F00000QkOpC-MyFeature543-
          prefix: SAMDEV
          standardFeature: false
          versions:
            '1':
              modifiedDate: '2020-02-17 13:28:44'
        01p6F00000QkOpC-TEST-UI:
          path: 01p6F00000QkOpC-TEST-UI
          prefix: nCino
          standardFeature: true
          versions:
            '1':
              modifiedDate: '2020-02-18 06:27:19'
        01p6F00000QkOpC-Jan24-Test4:
          path: 01p6F00000QkOpC-Jan24-Test4
          prefix: ncino-
          standardFeature: true
          versions:
            '24.2':
              modifiedDate: '2020-02-18 06:33:19'
