!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    ? ''
    : features:
        01p6F00000QkOpC-Credit Memo:
          path: /01p6F00000QkOpC-Credit Memo
          prefix: SAMDEV
          versions:
            Version-1.0:
              modifiedDate: '2020-02-14 07:00:53'
            Version-2.0:
              modifiedDate: '2020-02-14 07:24:16'
