!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        0100sBg1100110vRvD-Credit Memo:
          path: dataset/0100sBg1100110vRvD-Credit Memo
          prefix: SAM-DEVBOX
          versions:
            Version-1.0:
              modifiedDate: '2020-02-03 15:16:20'
            Version-2.0:
              modifiedDate: '2020-02-03 15:19:02'
